# Generated by Django 5.2.7 on 2025-10-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='position',
            field=models.CharField(choices=[('Chairperson', 'Chairperson'), ('Vice Chairperson', 'Vice Chairperson'), ('Secretary ', 'Secretary'), ('Treasurer', 'Treasurer'), ('IT & Technical Lead', 'IT & Technical Lead'), ('Class Representative', 'Class Representative')], max_length=50),
        ),
    ]
