# Generated by Django 5.2.7 on 2025-10-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_leader_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='position',
            field=models.CharField(choices=[('Chairperson', 'Chairperson'), ('Vice Chairperson', 'Vice Chairperson'), ('Organising Secretary', 'Organising Secretary'), ('Secretary ', 'Secretary'), ('Treasurer', 'Treasurer'), ('IT Manager', 'IT Manager'), ('Class Representative', 'Class Representative')], max_length=50),
        ),
    ]
