# Generated by Django 5.2.7 on 2025-10-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
