# Generated by Django 5.2.7 on 2025-10-20 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('notes', 'Study Notes'), ('exam_prep', 'Exam Preparation'), ('reading', 'Reading Materials'), ('career', 'Career Resources'), ('internship', 'Internship Info'), ('professional', 'Professional Tips'), ('newsletter', 'Newsletter'), ('past_paper', 'Past Papers'), ('report', 'Reports')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to='resources/')),
                ('external_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resourcecategory')),
            ],
        ),
    ]
